# fly.toml app configuration file generated for kid-adventure-api-seeyeah on 2026-06-03T14:23:34+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kid-adventure-api-seeyeah'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  API_PREFIX = '/api/v1'
  APP_ENV = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
